# Generated by Django 2.2.5 on 2019-10-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'M'), ('Feminino', 'F')], default='M', max_length=1)),
            ],
        ),
    ]
