# Generated by Django 2.2.6 on 2019-10-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20191001_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='imagem',
            field=models.ImageField(blank=True, default=1, upload_to='pessoas'),
            preserve_default=False,
        ),
    ]
