# Generated by Django 2.2.6 on 2019-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20191003_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pessoas'),
        ),
    ]
