# Generated by Django 2.2.6 on 2019-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treinamento',
            options={'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='treinamentos'),
        ),
    ]
